version:  '3.3'
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics check_running
            interval: 30s
            timeout: 30s
            retries: 3
        restart: always
        hostname: rabbitmq
        ports:
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: "/"
    service:
        container_name: service
        depends_on:
            rabbitmq:
                condition: service_healthy
            mysql:
                condition: service_healthy
        image: marjugoncalves/blur-service:2.0
        restart: always
        ports:
            - 8080:8080
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_MASTER: ${MYSQL_MASTER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_METADATA_TABLE: ${MYSQL_METADATA_TABLE}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: ${AWS_REGION}
            AWS_BUCKET: ${AWS_BUCKET}
    worker:
        depends_on:
            - rabbitmq
        image: marjugoncalves/blur-worker:2.0
        container_name: worker
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_BUCKET: ${AWS_BUCKET}
    mysql:
        depends_on:
            - rabbitmq
        image: mysql:8.0
        container_name: mysql
        healthcheck:
            test: "/usr/bin/mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
            timeout: 200s
            interval: 10s
            retries: 20
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
