version:  '3.3'
services:
    blur-rabbitmq:
        image: rabbitmq:3-management
        container_name: blur-rabbitmq
        restart: always
        hostname: rabbitmq
        ports:
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: "/"
    blur-service:
        depends_on:
            - blur-rabbitmq
        build: .
        container_name: blur-service
        restart: always
        volumes:
            #use normal volumes later
            - type: bind
              source: /Users/marcelo/Desktop/source-images
              target: /source-images
        ports:
            - 8080:8080
        environment:
            AMQP_URL: ${AMQP_URL}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_METADATA_TABLE: ${MYSQL_METADATA_TABLE}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: ${AWS_REGION}
            AWS_BUCKET: ${AWS_BUCKET}
    blur-worker:
        depends_on:
            - blur-rabbitmq
        build: worker/
        container_name: blur-worker
        restart: always
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        volumes:
            #use normal volumes later
            - type: bind
              source: /Users/marcelo/Desktop/source-images
              target: /source-images
            - type: bind
              source: /Users/marcelo/Desktop/blurred-images
              target: /blurred-images
    blur-mysql:
        depends_on:
            - blur-rabbitmq
        image: mysql:8.0
        build: sql/
        container_name: blur-mysql
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - type: bind
              source: /Users/marcelo/Desktop/blur-mysql
              target: /var/lib/mysql
