apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.labels }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
      nodePort: {{ .Values.ports.nodePort }}
  type: NodePort