apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      initContainers:
      - name: {{ .Values.initContainers.name }}
        image: {{ .Values.initContainers.image }}
        command: ['sh', '-c',
        'until wget http://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq:15672/api/aliveness-test/%2F; 
        do echo waiting; sleep 2; done;']
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.ports.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
        volumeMounts:
        - name: {{ .Values.volumes.name }}
          mountPath: {{ .Values.volumeMounts.original }}
        - name: {{ .Values.volumes.name }}
          mountPath: {{ .Values.volumeMounts.blurred }}  
      volumes:
      - name: {{ .Values.volumes.name }}
        hostPath:
          path: {{ .Values.volumes.hostPath }}
      - name: {{ .Values.volumes.name }}
        hostPath:
          path: {{ .Values.volumes.hostPath }}
        