apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker
spec:
  selector:
    matchLabels:
      app: blur
  template:
    metadata:
      labels:
        app: blur
    spec:
      containers:
      - name: worker
        image: marjugoncalves/blur-worker 
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
          name: worker-configmap