deployment:
  minReplicas: 1
  maxReplicas: 3
  image: marjugoncalves/blur-worker:2.0
name: worker 
labels: blur-worker
initContainers:
  image: busybox:1.31.1
  name: check-rabbitmq
ports:
  port: 8081
  targetPort: 8081
volumes:
  name1: source-images
  name2: blurred-images
  hostpath: /home/docker
volumeMounts:
  original: /source-images
  blurred: /blurred-images
