apiVersion: v1
kind: Service
metadata:
  name: webservice-svc
spec:
  selector:
    app: blur
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort