apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: blur
  template:
    metadata:
      labels:
        app: blur
    spec:
      containers:
      - name: blur
        image: rabbitmq:3-management
        ports:
          - containerPort: 5672
          - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_pwd
        - name: RABBITMQ_DEFAULT_VHOST
          valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_vhost
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate