apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
spec:
  selector:
    matchLabels:
      app: blur
  template:
    metadata:
      labels:
        app: blur
    spec:
      initContainers:
      - name: check-rabbitmq
        image: busybox
        command: ['sh', '-c',
        'until wget http://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASSWORD)@rabbitmq:15672/api/aliveness-test/%2F;
        do echo waiting; sleep 2; done;']
        env:
          - name: RABBITMQ_USER
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_user
          - name: RABBITMQ_PWD
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_pwd
      - name: check-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: blur-service
        image: marjugoncalves/blur-service
        ports:
        - containerPort: 8080   
        envFrom:
        - configMapRef:
          name: webservice-configmap