deployment:
  image: marjugoncalves/blur-service:2.0
  minReplicas: 1
  maxReplicas: 5
name: webservice
labels: blur-service
ports:
  port: 8080
  containerPort: 8080
  targetPort: 8080
  nodePort: 30002
initContainers:
  image: busybox:1.31.1