apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
spec:
  selector:
    matchLabels:
      app: blur
  template:
    metadata:
      labels:
        app: blur
    spec:
      initContainers:
      - name: check-rabbitmq
        image: busybox
        command: ['sh', '-c',
        'until wget http://$(RABBITMQ_USER):$(RABBITMQ_PWD)@rabbitmq:15672/api/aliveness-test/%2F;
        do echo waiting; sleep 2; done;']
        env:
          - name: RABBITMQ_USER
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_user
          - name: RABBITMQ_PWD
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_pwd
      - name: check-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: blur-service
        image: marjugoncalves/blur-service
        ports:
        - containerPort: 8080   
        env:
          - name: RABBITMQ_USER
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_user
          - name: RABBITMQ_PWD
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_pwd
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_host
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_port
          - name: RABBITMQ_QUEUE
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: rabbitmq_queue
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: mysql_user 
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: mysql_password 
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: webservice-secrets
                key: mysql_database
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: aws_access_key_id 
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: aws_secret_access_key
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: aws_region 
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: blur-configmap
                key: aws_bucket