FROM python:3.8-alpine

LABEL version="0.0.1"

RUN apk add --update-cache \
    build-base \
    cmake \
    jpeg-dev \
    py-pip \
    zlib-dev \
    && pip install --upgrade pip \
    && rm -rf /var/cache/apk/*

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN adduser -D worker

USER worker

COPY . /home/worker 

ENTRYPOINT python /home/worker/worker.py

VOLUME ["/source-images", "/blurred-images"]

# FROM alpine:3.12

# LABEL version="0.0.1"

# RUN apt-get update && apt-get install -y \
#     cmake \
#     g++ \
#     && pip install --upgrade pip

# COPY requirements.txt .

# RUN pip install -r requirements.txt 

# WORKDIR /app

# COPY . .

# ENTRYPOINT python worker.py

# VOLUME ["/source-images", "/blurred-images"]

